### ISSUE TITLE
Running synclounge offline

### ISSUE THREAD

**Issue by nkfs** [samcm/synclounge#122]
I've installed synclounge via docker container successfully and have connected it to my plex server successfully as well. I was wondering if there was a way to make it work offline (without internet).  I am trying to sync multiple screens on multiple accounts that are connected to my one server.

Thanks

**Comment by samcm** [comment]
The app authenticates against plex.tv which in turn handles our server/client discovery. Because we're in a browser environment the other methods of discovery are off limits and we'd have to fall back to manually entering client/server details.

In short it's possible but not without some sacrifices.

**Comment by redondo-se** [comment]
I was thinking about trying this for in-car synchronized video playback on android tablets. But, the car hotspot won't have internet access. Could this work?
