### ISSUE TITLE
Emby Support?

### ISSUE THREAD

**Issue by aschneid1** [samcm/synclounge#123]
Is there any possibility for future support with Emby?  I prefer Emby to Plex for various reasons, but this project would be really nice to have (I recently moved and it would be a great way to stay in touch with friends and people who use my emby server).  The developers of Emby have recently expressed willingness to share their API with you if it would help.

Thanks!

**Comment by samcm** [comment]
Heya, we're definitely open to adding support for other platforms. While the project is pretty coupled to Plex at the moment, breaking that apart shouldn't be too hard. Unfortuantely it's unlikely to happen in the near future due to how much free time @gcordalis and I have at the moment with work. 😢

**Comment by aschneid1** [comment]
I'm primarily a C++ developer and don't have a ton of experience with JS, but I'd be willing to take a shot at this.  Do you have any idea how you would begin or how the structure of the code would have to change to accommodate Emby?

**Comment by oliver-ni** [comment]
I could give this a try, not sure how hard it would be though. Would need to look further into the inner workings
