### ISSUE TITLE
Unable to access SyncLounge outside my network

### ISSUE THREAD

**Issue by climber514** [samcm/synclounge#152]
Hello All!

I set up a room, get a movie going and no issues.   I send an invite to myself to check via cellular and I get the error "Unable to connect; try disabling your adblocker"   I dont have an adblocker on my phone.   I sent an invite to a friend and they get the same message no matter what device they are on (android, ipad, iphone and pi)

They do have access to my plex server as we tested it out again on multiple devices and they can watch no problem, just not using the synclounge.

Any suggestions as to what would be causing it the adblocker error or just the not connecting when not connected to my network?

Thanks in advance!

Peace

**Comment by samcm** [comment]
Heya,

Is there anything special about your Plex server setup? Behind a reverse proxy or something like that? Unfortunately we're pretty limited in what the browser provides when CORS requests fail which is what would be happening here.

**Comment by realansgar** [comment]
Same here, my Plex server is reachable outside the home network by several Plex players (Web, Android) but not reachable by Synclounge. The tricky part is, that my Plex server says that it's not reachable from the outside in the settings despite being reachable. This is due to my local network being forced to use DS-Lite by my ISP. I have a publicly visible IPv4 address that is actually owned by my ISP, not by my local network. I also have IPv6 addresses for all network devices and apparently the Plex players can figure out how to connect via that but not Synclounge. At least that's my guess.

**Comment by cecoates** [comment]
I'm not sure if this should be a new issue, but I'm also unable to connect to my server from outside the network.

In the console there are lots of timeout/websocket errors. If I am able to connect to the server, and try to join/create a room, it goes through this infinite loop of joining/quitting.

I tried to blur out anything that was private/tokens/etc. but I wasn't sure, so let me know if I overcensored or undercensored something.

![slerrors](https://user-images.githubusercontent.com/10121835/80784279-14208780-8b42-11ea-9bc8-4dc08d0d4c72.jpg)

The webapp at 8088 seems to work fine, and I'm able to access my Plex server from outside my network fine. It's specifically the SyncLounge server part that's giving me trouble.

I'm running SL in a Docker container on a QNAP NAS, with default values for everything.

I've also made sure my router is forwarding the correct ports.

Does this seem related to the above folks as well?
