### ISSUE TITLE
[Feature Request] API endpoint for room queries.

### ISSUE THREAD

**Issue by CyaOnDaNet** [samcm/synclounge#178]
I have a discord server for my Plex users and would love to implement a notification system for when people are active in a self-hosted room. I am well-versed in making discord bots but I need an API to pull the data from. Some ideas for what I would like to see in a REST API endpoint would be:

- Boolean value for if the self-hosted room is active/ has people in it
- User Information
  - Number of users in a room
  - List of Plex usernames
  - Who the leader of the room is
- The media being played
  - imdb id or tvdb id so other info can be easily queried
  - Current timestamps
- Chat History

Thanks for your work. I have been self-hosting my own rooms for a few weeks and it seems to work pretty well.

**Comment by samcm** [comment]
This shouldn't be too hard actually. We don't handle imdb/tvdb ids at the moment, largely because they were a pain and/or non-existent in some of the Plex APIs at the time. There is a title etc though. Nearly all of your required info could be figured out by returning all users in the room.

The only blocker might be security. We'd have to setup PSK auth or something so that this info isn't publicly accessible on the public servers. I was planning on doing this anyway so 👌
