### ISSUE TITLE
Unable to access shared libraries

### ISSUE THREAD

**Issue by grendel06** [samcm/synclounge#67]
Hi!

I would like to share a problem that I experienced. I can access my plex server via another computer out of my lan both on my account and my friend's account which has permission to access my library. It is possible both on Plex Media Player and browser. But whenever we try to watch something together via SyncLounge, my friend saw the "unable to connect" problem under my library name.

**Tried Solutions**
*Tried starting SyncLounge with SL, Browser and Plex Media Server Clients for both computer.
*As for browser, Firefox and Chrome have been used.

_Result:_ When the lobby leader-library owner- (in this case my friend) starts a video, on my computer it says "failed to find a compatible copy of [The video Name Here] on the browser and on Plex Media Player it starts and stops immediately in every 10 seconds approximately.

_Result:_ When I (not lobby leader in this case) start a video from my own library, the video starts on other persons computer and from lobby I can see the progress but nothing happens on my computer.

_Result:_ When the lobby leader -having My Shared Library- starts a video from my library, on my computer movie starts and stops immediately in every 10 seconds approximately on Plex Media Player.

_Common Result:_ The person who has access to other person's shared library can watch anything from the shared library on Plex Media Player.

I'm willing to help and open to provide info on this issue for solving the problem.

**Comment by samcm** [comment]
Hey, thanks for the detailed issue report. The core of the issue is the `unable to connect` error so let's try and sort that out first. 

Are you using your own install of SL or app.synclounge.tv? 
Plex Media Server behind a reverse-proxy? 
Adblockers disabled? 

You could also check the browser console logs on your friends computer when starting up SL. It may reveal some info on why the connection is failing. Don't directly copy paste anything though as Plex Tokens are embedded in URLs. 

The reason this is happening is SL is very reliant on retrieving metadata from PMS for the currently playing content. If this process fails, it believes the client is playing the wrong item (or nothing at all) and will look to remedy it.
