### ISSUE TITLE
Option to sync playback for all members in a room?

### ISSUE THREAD

**Issue by vortexrap** [samcm/synclounge#71]
In the current version, if a user pauses playback and resumes, the user has to close out of the app and reconnect to get the back in sync - most times the host has to pause and wait for the user to join back for the sync to work. 

There should be easy ways for the host to control sync and the user to re-sync:

- Option for room host to sync all room users to position of the room host
- Option for users to jump to the current position of the room host

Both options could be implemented via a button in the sync lounge player next to playback settings / stop playback. I am not sure how to manage this on other clients - first thoughts include a dedicated synclounge app or webapp that would provide the functionality.

**Comment by samcm** [comment]
The users in the room should be trying to constantly stay in sync - they should never have to close the app and rejoin to resync. If they don't sync, the deviation is either within an acceptable range (determined by the `Sync Flexibility` option in SyncLounge Settings in the top left), or something is blocking the sync. It's at 3000ms by default, but you could probably get by with sub-1000ms if your conditions permitted it. 

The only situation a block occurs is when the built-in player is doing a speed-up sync - where the playback rate is change slightly so the user doesnt notice the sync happening. This usually clears itself up after about 30s and can't be interrupted once it starts. This is fixed in v2. 

As for the manual buttons, a couple people have requested them and I can definitely implement it for v2.   However the hope is that the improvements to the code in v2 will reduce the situations where they are necessary - especially with the built-in player.

**Comment by vortexrap** [comment]
Closing this as this is a feature in V2. Thanks!
