### ISSUE TITLE
Host/Guest syncing issues

### ISSUE THREAD

**Issue by teknoziz** [samcm/synclounge#73]
I have a friend spending a year in South Korea, and we use sync lounge to both chat and co-watch shows. A couple of questions. Should it matter who is host and who is guest? Should we pick a more centrally located server (aka Europe)? Does it matter what browser we are both using? I own the Plex account, but today he seemed to be the host. Is there a way to switch without having to leave the room? Is your code synced with the Plex beta channel and could it affect how Sync Lounge works? It seemed to work better the previous time we used it before the recent Plex update. Sorry for all the questions. Let me know if there is a better place to send this.

**Comment by gcordalis** [comment]
[Discord](https://discord.gg/fKQB3yt) might be easier to discuss these issues, but this works too.

- It shouldn't matter who is host or guest. 
- Your mileage will vary between servers, the dev team is based in Australia/New Zealand and we've had no issues using the NA server instead of AU despite it making less sense geographically.
- Double clicking a user's picture as the host will make them the host. They can do the same to give it back.
- Unless Plex changes something dramatic between versions there shouldn't be much difference between Plex stable and beta channels. Of course mileage will vary with this too.

**Comment by teknoziz** [comment]
Thanks for your quick response! My friend did mention that his connection is sometimes spotty. So that could be it. We will see what happens. We are watching just standard def shows right now.
Sincerely,

 



David Zizza, TeKno Ziz
(617) 543-3971 cell     (978) 663-0951 home office
david@teknoziz.com <mailto:david@teknoziz.com> teknoziz.com <https://teknoziz.com/>
