### ISSUE TITLE
Unable to watch more than a few minutes.

### ISSUE THREAD

**Issue by serfilian** [samcm/synclounge#78]
I keep getting an error message displayed on top of my screen when I am playing movies from my server that says the following:
> Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

It only seems to happen with some videos, and on some videos I can watch a good deal of it without any issues, but on others I can't even go more than 5 minutes without the error coming up. Strangely enough, this issue is not also happening to the person with whom I am viewing the video.
![An example of the error](https://user-images.githubusercontent.com/15863243/42149565-5daf02ba-7d9c-11e8-9882-b1d8d01dd2eb.jpg)

I've tried running it without extensions as well as on freshly installed browsers, as well as trying to restart my server, but to no avail. This even happens when i am watching the video by myself.

**Comment by serfilian** [comment]
Ah, ok that seems to work. Thanks!

**Comment by Baxxster** [comment]
Are there no alternative solutions to this yet?

**Comment by ttshivers** [comment]
Why does synclounge have this issue but the regular plex web player not?

**Comment by gcordalis** [comment]
Plex has most likely developed their own video player whereas we rely on an open source one for SyncLounge.
We don't have the time available to develop our own unfortunately.

**Comment by ttshivers** [comment]
I've been looking into it a little more and found the issue but not an easy fix yet because it comes from a package being deprecated.
The issue comes from `videojs-contrib-hls`, which is a dependency of both synclounge and `vue-video-player`. Unfortunately `videojs-contrib-hls` has been archived before a pull request that fixes this issue was merged https://github.com/videojs/videojs-contrib-hls/pull/1416. It was deprecated in favor of https://github.com/videojs/http-streaming. 

Unfortunately `vue-video-player` has not updated to the new package so it still has this issue.

**Comment by Cookie-Monster-Coder** [comment]
Any update on this? Keep getting it on both Firefox and Chrome. Thanks!

**Comment by ttshivers** [comment]
So, unforutnately even in the most recent builds of videojs, these issues still persist. I am keeping on top of this and rolling my own synclounge with the latest builds to see if it does get fixed. The latest comment I saw on the issue was: https://github.com/videojs/video.js/issues/5408#issuecomment-607479583

**Comment by Cookie-Monster-Coder** [comment]
Issue still exist and is not stale.

**Comment by ccristob** [comment]
Yes, issue still exists on latest versions of Chrome and Firefox

**Comment by ttshivers** [comment]
We are aware of the issue and have a fix for it in the next release

**Comment by Cookie-Monster-Coder** [comment]
> We are aware of the issue and have a fix for it in the next release

Any idea on when the next release is pushed?

**Comment by ttshivers** [comment]
If you do decide to try out that branch, leave comments if you find any bugs.

**Comment by ttshivers** [comment]
This PR is incorporated into my other much larger PR that overhauls much #220
