### ISSUE TITLE
Path prefix gone

### ISSUE THREAD

**Issue by rix1337** [samcm/synclounge#85]
Hi, I wrote this on reddit a while back:
basically I am running a dozen Apps on my domain. None of which require a subdomain to be used, because I am able to set up a path prefix. Sonarr for example runs at /sonarr, Plex at /web

I cannot run v2.0 in my setup right now, since /ptweb is gone.

**Please give us an option to select a path prefix. I would gladly include it iny my docker container: https://hub.docker.com/r/rix1337/docker-synclounge-auto/**

**Comment by samcm** [comment]
Heya,

All of the above (including autojoin) is actually in v2 now, it's just undocumented at the moment. Largely because I'm not 100% locked in on how to do things. At the moment you can change the path of the webapp via `webroot`, and the path of the server with `serverroot`. You can set these either in the ENV or with a command line argument. If you want an example you can have a look here: https://github.com/Starbix/docker-synclounge/blob/master/alpine/run.sh. It's not very tidy but that's largely due to the WIP status of v2.

I sent you a PM on Reddit a couple weeks ago to ask for input on how to implement autojoin/paths but didn't hear back :(

I'll 100% document all of this within this repo wiki once we're at a more finalized stage of v2.

**Comment by rix1337** [comment]
Sorry, that reply must have slipped through. The ENV solution will be working fine for me. No more fiddling with sed :+1: 

Thanks for the very quick reply!

**Comment by rix1337** [comment]
Thanks for your update. This is working very well. Glad to have upgraded to v.2.0

Thanks for your hard work!
