### ISSUE TITLE
Debugging Apple TV connection errors

### ISSUE THREAD

**Issue by olivierlacan** [samcm/synclounge#96]
From https://v2.synclounge.tv/#/clientselect are there some debugging steps one could take to debug failed connections to Apple TV clients? 

The console error printed doesn't leave much room for troubleshooting currently. It doesn't display what IP address was tried or details about the HTTP request itself that could help with debugging?

Thanks.

**Comment by samcm** [comment]
Heya,

There should be some more info in the Network debug tab which should give some more info. I'm actually not sure what `v2.synclounge.tv` points to, i'm pretty sure it's just forwarding to `app.synclounge.tv` because v2 is in master now but maybe try with that url just so we're on the same page :)
